<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-8EA77APH" ignored="0" name="Test" tests="6" failures="1" timestamp="28 Oct 2021 09:49:21 GMT" time="0.081" errors="0">
  <testcase name="tc1" time="0.016" classname="org.dataprovider.TestCase"/>
  <testcase name="tc2" time="0.001" classname="org.dataprovider.TestCase">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.0" classname="org.dataprovider.TestCase">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.0" classname="org.dataprovider.TestCase">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.0" classname="org.dataprovider.TestCase">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.dataprovider.TestCase.tc2(TestCase.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase name="tc3" time="0.0" classname="org.dataprovider.TestCase"/>
</testsuite> <!-- Test -->
